 language: node_js
 node_js:
  - "0.10"
services:
  - redis-server
branches:
  only:
    - master
before_script:
  - echo ====================================================
  - netstat -nlp4
script: npm test
